#include "my_robot_controller/cascaded_pid_controller.hpp"

#include "my_robot_controller/path_reference_manager.hpp"

#include <algorithm>
#include <cmath>
#include <stdexcept>

namespace my_robot_controller
{

CascadedPidController::CascadedPidController(const CascadedPidConfig & config)
{
  configure(config);
}

void CascadedPidController::validate_config(const CascadedPidConfig & config) const
{
  const bool gains_are_finite =
    std::isfinite(config.cross_track_kp) && std::isfinite(config.cross_track_ki) &&
    std::isfinite(config.cross_track_kd) &&
    std::isfinite(config.cross_track_integral_limit) &&
    std::isfinite(config.heading_kp) && std::isfinite(config.heading_ki) &&
    std::isfinite(config.heading_kd) && std::isfinite(config.heading_integral_limit);
  if (!gains_are_finite) {
    throw std::invalid_argument("Cascaded PID gains and integral limits must be finite");
  }

  if (!std::isfinite(config.maximum_heading_correction) ||
    config.maximum_heading_correction <= 0.0)
  {
    throw std::invalid_argument("maximum_heading_correction must be finite and positive");
  }
  if (!std::isfinite(config.cross_track_speed_gain) || config.cross_track_speed_gain < 0.0) {
    throw std::invalid_argument("cross_track_speed_gain must be finite and non-negative");
  }
  if (!std::isfinite(config.maximum_linear_velocity) ||
    config.maximum_linear_velocity <= 0.0 ||
    !std::isfinite(config.maximum_angular_velocity) ||
    config.maximum_angular_velocity <= 0.0)
  {
    throw std::invalid_argument("Cascaded PID command limits must be finite and positive");
  }
}

void CascadedPidController::configure(const CascadedPidConfig & config)
{
  validate_config(config);
  config_ = config;
  cross_track_pid_.configure(
    config.cross_track_kp, config.cross_track_ki, config.cross_track_kd,
    config.cross_track_integral_limit);
  heading_pid_.configure(
    config.heading_kp, config.heading_ki, config.heading_kd,
    config.heading_integral_limit);
}

CascadedPidOutput CascadedPidController::calculate(
  double cross_track_error,
  double path_heading,
  double robot_heading,
  double reference_linear_velocity,
  double reference_angular_velocity,
  double dt)
{
  if (!std::isfinite(cross_track_error) || !std::isfinite(path_heading) ||
    !std::isfinite(robot_heading) || !std::isfinite(reference_linear_velocity) ||
    !std::isfinite(reference_angular_velocity) || !std::isfinite(dt) || dt <= 0.0)
  {
    throw std::invalid_argument("Cascaded PID input and dt must be finite, with dt positive");
  }

  CascadedPidOutput output;

  // With the project's sign convention, cross-track error is positive on the
  // left side of the path tangent. Therefore a positive outer PID output must
  // create a negative (right-turning) heading correction.
  output.cross_track_pid_output = cross_track_pid_.calculate(cross_track_error, dt);
  output.heading_correction = std::clamp(
    -output.cross_track_pid_output,
    -config_.maximum_heading_correction,
    config_.maximum_heading_correction);
  output.desired_heading = wrap_angle(path_heading + output.heading_correction);

  // This inner error includes both path-tangent alignment and the outer-loop
  // lateral correction. A sudden robot rotation changes it immediately even
  // if cross-track error has not had time to grow.
  output.heading_error = wrap_angle(output.desired_heading - robot_heading);
  output.heading_pid_output = heading_pid_.calculate(output.heading_error, dt);
  output.angular_command = std::clamp(
    reference_angular_velocity + output.heading_pid_output,
    -config_.maximum_angular_velocity,
    config_.maximum_angular_velocity);

  // cos(error) smoothly reduces translation to zero at 90 degrees of heading
  // mismatch. The lateral factor also slows a displaced robot without changing
  // the common nominal/curvature/endpoint speed generated by the path manager.
  output.heading_speed_factor = std::max(0.0, std::cos(output.heading_error));
  output.cross_track_speed_factor =
    1.0 / (1.0 + config_.cross_track_speed_gain * std::abs(cross_track_error));
  output.linear_command = std::clamp(
    reference_linear_velocity * output.heading_speed_factor *
    output.cross_track_speed_factor,
    0.0, config_.maximum_linear_velocity);

  return output;
}

void CascadedPidController::reset()
{
  cross_track_pid_.reset();
  heading_pid_.reset();
}

}  // namespace my_robot_controller
